apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: argocd
  labels:
    environment: playground
spec:
  project: app
  source:
    path: k8s/namespace
    repoURL: https://github.com/otakakot/playground-argocd.git
    targetRevision: main
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
