apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: argocd
spec:
  project: playground
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: k8s/httpd
    repoURL: https://github.com/otakakot/playground-argocd.git
    targetRevision: main
  syncPolicy:
    automated: {}
