apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: httpd
    name: httpd
spec:
  type: NodePort
  ports:
  - name: httpd-port
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: httpd
